# src/EIPA/PlatformBundle/Resources/config/routing.yml

eipa_platform_home:
    path:      /{page}
    defaults:  { _controller: EIPAPlatformBundle:Advert:index, page: 1 }
    requirements:
        page: \d*

eipa_platform_view:
    path:      /advert/{id}
    defaults:  { _controller: EIPAPlatformBundle:Advert:view }
    requirements:
        id: \d+

eipa_platform_add:
    path:      /add
    defaults:  { _controller: EIPAPlatformBundle:Advert:add }

eipa_platform_edit:
    path:      /edit/{id}
    defaults:  { _controller: EIPAPlatformBundle:Advert:edit }
    requirements:
        id: \d+

eipa_platform_delete:
    path:      /delete/{id}
    defaults:  { _controller: EIPAPlatformBundle:Advert:delete }
    requirements:
        id: \d+